<?php
// auth-generated by ModuleConfigHandler
// date: 12/18/2018 14:59:00
define('MOD_USERLIST_ENABLED', true);
define('MOD_USERLIST_TITLE', 'userlist Mojavi Module');
define('MOD_USERLIST_VERSION', 1.0);
define('MOD_USERLIST_NAME', 'userlist');
define('MOD_USERLIST_AUTHOR', 'fly');
define('MOD_USERLIST_HOMEPAGE', null);
define('MOD_USERLIST_UPDATE_URL', null);
define('MOD_USERLIST_DESCRIPTION', 'userlist Mojavi Module');
?>