<?php
// auth-generated by FilterConfigHandler
// date: 12/17/2018 16:41:04
require_once('/Applications/XAMPP/xamppfiles/htdocs/laiketui/app/install/webapp/filter/LoginFilter.class.php');
require_once('/Applications/XAMPP/xamppfiles/htdocs/laiketui/app/install/webapp/filter/ThdFilter.class.php');
require_once('/Applications/XAMPP/xamppfiles/htdocs/laiketui/app/install/webapp/filter/SedFilter.class.php');
$filters = array();
$filter = new ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$filter = new LoginFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new ThdFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new SedFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>